name: My-workflow

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 1
    steps:
      - uses: actions/checkout@v4

      - name: Listing files and reading files
        run: |
          ls -lart
          [ -f README.md ] && cat README.md || echo "No README found"
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Use password securely
      run: |
        if [ -z "$PASSWORD" ]; then
        echo "Password missing"
        exit 1
        fi
        echo "Password exists, proceeding..."
    env:
        PASSWORD: ${{ secrets.PASSWORD }}